
import {
  BarChart, 
  Book, 
  Calendar, 
  ChevronDown,
  FileText, 
  Home, 
  Library, 
  LogOut, 
  School, 
  Settings, 
  ShoppingBag, 
  User, 
  Users,
  Bell,
  Bus,
  Coffee,
  Footprints,
  Building,
  HelpCircle,
  Inbox,
  BookOpen,
  Activity,
  DollarSign,
  Ticket
} from "lucide-react";

export const Icons = {
  dashboard: Home,
  school: School,
  classes: Book,
  sessions: Calendar,
  settings: Settings,
  inquiries: HelpCircle,
  logs: FileText,
  manageClassSections: Building,
  manageMedium: Book,
  manageStudentType: Users,
  subjects: BookOpen,
  classTimeTable: Calendar,
  attendance: Users,
  studentLeaves: Calendar,
  studyMaterials: FileText,
  homework: Book,
  noticeboard: Bell,
  event: Calendar,
  liveClasses: Activity,
  staffRatting: Users,
  studentBirthdays: Calendar,
  admission: User,
  students: Users,
  idCards: FileText,
  promote: Activity,
  transferStudent: Users,
  certificates: FileText,
  notifications: Bell,
  admins: Users,
  roles: Users,
  staffList: Users,
  staffAttendance: Users,
  staffLeaves: Calendar,
  income: DollarSign,
  expenses: DollarSign,
  feeInvoices: FileText,
  collectPayments: DollarSign,
  feeTypes: FileText,
  bulkInvoicePrints: FileText,
  invoicesReport: BarChart,
  manageExams: Book,
  manageGroups: Users,
  admitCards: FileText,
  admitCardsBulkPrint: FileText,
  examResults: BarChart,
  bulkPrintResults: FileText,
  academicReport: BarChart,
  vehicles: Bus,
  routes: Bus,
  report: BarChart,
  activities: Footprints,
  hostels: Building,
  rooms: Building,
  lessons: Book,
  chapters: BookOpen,
  tickets: Ticket,
  allBooks: Book,
  booksIssued: Book,
  libraryCards: Library,
  chevronDown: ChevronDown,
  logout: LogOut,
  book: Book,
  users: Users,
  dollarSign: DollarSign,
  fileText: FileText,
  bus: Bus,
  building: Building,
  ticket: Ticket,
  library: Library,
  helpCircle: HelpCircle,
  home: Home
};
